[tool.poetry]
name = "nuvlaedge"
version = "0.1.0"
description = "NuvlaEdge source code"
authors = ["Nacho <nacho@sixsq.com>"]
readme = "README.md"
packages = [{include = "nuvlaedge"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "1.10.7"
nuvla-api = "3.0.8"
# Common library deps
filelock = "3.12.0"

[tool.poetry.group.tests.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
mock = "^5.0.2"


[tool.poetry.group.system_manager.dependencies]
docker = "^6.1.1"
kubernetes = "^26.1.0"
cryptography = "^40.0.2"
pyopenssl = "^23.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
