[tool.poetry]
name = "nuvlaedge"
version = "0.1.0"
description = ""
authors = ["Nacho <nacho@sixsq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "1.10.7"
nuvla-api = "3.0.8"


[tool.poetry.group.tests.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
mock = "^5.0.2"


[tool.poetry.group.common-lib.dependencies]
filelock = "3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
