# Builds the python wheel package and the NuvlaEdge base image and publishes
# it into nuvladev/ dockerhub registry

name: "Build NuvlaEdge Image"

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - run: echo "HelloWorld from build"
#  push:
#    branches:
#      - 'main'
#    paths:
#      - 'nuvlaedge/'
#      - 'Dockerfile'
#
#  pull_request:
#    paths:
#      - 'nuvlaedge/'
#      - 'Dockerfile'
